apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: habit-tracker
  labels:
    app: habit-tracker-backend
spec:
  type: ClusterIP
  selector:
    app: habit-tracker-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  sessionAffinity: ClientIP
