apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: habit-tracker
  labels:
    app: habit-tracker-backend
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "django-insecure-change-this-in-production-k8s-secret-key-12345"
  # Para producci√≥n real, usar PostgreSQL:
  # DATABASE_URL: "postgresql://user:password@postgres-service:5432/habitdb"
