apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: habit-tracker
  labels:
    app: habit-tracker-backend
data:
  DJANGO_SETTINGS_MODULE: "habit_tracker_backend.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://frontend-service"
  DATABASE_ENGINE: "django.db.backends.sqlite3"
  DATABASE_NAME: "/app/db.sqlite3"
