apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: habit-tracker
  labels:
    app: habit-tracker-frontend
spec:
  type: LoadBalancer
  selector:
    app: habit-tracker-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
